[versions]
androidxFoundation = "1.4.3"
androidxMaterial = "1.7.4"
androidxNavigationNavigationCompose = "2.7.0"
androidxUi = "1.4.3"
appcompat = "1.6.1"
composeCompiler = "1.5.15"
composeRuntime = "1.7.5"
converterGson = "2.9.0"
converterScalars = "2.1.0"
coreKtxVersion = "1.12.0"
activityComposeVersion = "1.7.2"
agp = "8.2.0"
androidxComposeMaterial3Material3 = "<1.3.0>"
androidxMaterial3 = "1.1.0-alpha06"
androidxMaterial3Version = "<2.9.0>"
androidxMaterialVersion = "1.4.3"
androidxNavigationCompose = "2.8.1"
androidxNavigationComposeVersion = "<1.3.0>"
androidxNavigationNavigationCompose2 = "2.7.3"
appcompatVersion = "1.7.0"
coilCompose = "2.0.0"
coilComposeVersion = "2.1.0"
foundation = "1.7.1"
foundationVersion = "1.6.0"
hiltVersion = "2.50"
hiltNavigationCompose = "1.2.0"
jetbrainsKotlinxCoroutinesAndroid = "1.8.1"
kotlin = "1.9.0"
coreKtx = "1.13.1"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
kotlinStdlib = "1.9.22"
kotlinStdlibVersion = "1.9.0"
kotlinxCoroutinesAndroid = "1.7.3"
kotlinxCoroutinesAndroidVersion = "1.6.0"
kotlinxCoroutinesCore = "1.7.3"
kotlinxCoroutinesCoreVersion = "1.6.0"
lifecycleRuntimeKtx = "2.8.5"
activityCompose = "1.9.2"
composeBom = "2024.04.01"
loggingInterceptor = "4.10.0"
loggingInterceptorVersion = "4.9.1"
material = "1.12.0"
material3 = "1.3.0"
material3Version = "1.1.0"
materialIconsExtended = "1.7.2"
materialVersion = "1.7.1"
navigationCompose = "2.8.0"
navigationComposeVersion = "2.6.0-alpha01"
okhttp = "4.11.0"
okhttpVersion = "<4.11.0>"
playServicesAds = "23.3.0"
squareupConverterGson = "2.10.0"
squareupRetrofit = "2.10.0"
threetenabp = "1.3.1"
ui = "1.7.1"
uiTooling = "1.7.4"
uiToolingPreview = "1.7.1"
uiToolingPreviewVersion = "1.6.0"
uiVersion = "1.6.0"
viewpager2 = "1.1.0"
mediationTestSuite = "3.0.0"
compose = "1.4.3"
material3Android = "1.3.0"
identityJvm = "202408.1"
uiGraphicsAndroid = "1.7.4"
preferenceKtx = "1.2.1"
androidxCoreKtx = "1.2.0"
navigationRuntime = "2.8.0"
hiltCommon = "1.2.0"

[libraries]
androidx-appcompat-v161 = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "composeRuntime" }
androidx-core-ktx-v1120 = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
androidx-foundation-v143 = { module = "androidx.compose.foundation:foundation", version.ref = "androidxFoundation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-material = { module = "androidx.compose.material:material", version.ref = "material" }

androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-material-v174 = { module = "androidx.compose.material:material", version.ref = "androidxMaterial" }
androidx-material3-v130 = { module = "androidx.compose.material3:material3", version.ref = "androidxComposeMaterial3Material3" }
androidx-navigation-compose-v130 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationComposeVersion" }
androidx-navigation-compose-v270 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationNavigationCompose" }
androidx-navigation-compose-v273 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationNavigationCompose2" }
androidx-navigation-compose-v281 = { module = "androidx.navigation:navigation-compose", version.ref = "androidxNavigationCompose" }
androidx-ui-v143 = { module = "androidx.compose.ui:ui", version.ref = "androidxUi" }
androidxComposeAnimation = { module = "androidx.compose.animation:animation", version = "1.7.2" }
androidx-activity-compose-v172 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "foundation" }
androidx-foundation-v160 = { module = "androidx.compose.foundation:foundation", version.ref = "foundationVersion" }
androidx-material-v171 = { module = "androidx.compose.material:material", version.ref = "materialVersion" }
androidx-material3-v110 = { module = "androidx.compose.material3:material3", version.ref = "material3Version" }
androidx-material3-v110alpha06 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3" }
androidx-material3-v290 = { module = "androidx.compose.material3:material3", version.ref = "androidxMaterial3Version" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-navigation-compose-v260alpha01 = { module = "androidx.navigation:navigation-compose", version.ref = "navigationComposeVersion" }
androidx-ui-tooling-preview-v160 = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreviewVersion" }
androidx-ui-v160 = { module = "androidx.compose.ui:ui", version.ref = "uiVersion" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-compose-v210 = { module = "io.coil-kt:coil-compose", version.ref = "coilComposeVersion" }
converter-gson-v290 = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converterGson" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltVersion" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltVersion" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-stdlib-v190 = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlinStdlibVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-android-v160 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroidVersion" }
kotlinx-coroutines-android-v181 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "jetbrainsKotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCore" }
kotlinx-coroutines-core-v160 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesCoreVersion" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
logging-interceptor-v491 = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptorVersion" }
material = { module = "com.google.android.material:material", version.ref = "material" }
material-v143 = { module = "androidx.compose.material:material", version.ref = "androidxMaterialVersion" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-v4110 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
squareup-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "squareupConverterGson" }
squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "squareupRetrofit" }
threetenabp = { module = "com.jakewharton.threetenabp:threetenabp", version.ref = "threetenabp" }
ui = { module = "androidx.compose.ui:ui", version.ref = "ui" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiTooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
mediation-test-suite = { group = "com.google.android.ads", name = "mediation-test-suite", version.ref = "mediationTestSuite" }
androidx-compose-material = { module = "androidx.compose.material:material", version = "1.7.2" }
androidx-material3-android = { group = "androidx.compose.material3", name = "material3-android", version.ref = "material3Android" }
identity-jvm = { group = "com.android.identity", name = "identity-jvm", version.ref = "identityJvm" }
androidx-ui-graphics-android = { group = "androidx.compose.ui", name = "ui-graphics-android", version.ref = "uiGraphicsAndroid" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-navigation-runtime = { group = "androidx.navigation", name = "navigation-runtime", version.ref = "navigationRuntime" }
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "hiltCommon" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt-android-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" }
android-library = { id = "com.android.library", version.ref = "agp" }

